### ISSUE TITLE
Pointer or not ?

### ISSUE THREAD

**Issue by Z-K11** [zulqarnain1o1/cryptrade#4]
bool processinput(int n)
{  
    int userop = n;
    switch (n){
        case 1:
        std::cout<<"You Pressed: "<<userop<<std::endl;
        printhelp();
        break;
        case 2:
        std::cout<<"You Pressed: "<<userop<<std::endl;
        stats();
        break;
        case 3:
        std::cout<<"You Pressed: "<<userop<<std::endl;
        ask();
        break;
        case 4:
        std::cout<<"You Pressed: "<<userop<<std::endl;
        bid();
        break;
        case 5:
        std::cout<<"You Pressed: "<<userop<<std::endl;
        wallet();
        break;
        case 6:
        std::cout<<"You Pressed: "<<userop<<std::endl;
        gonext();
        break;
        case 0:
        std::cout<<"You Pressed: "<<userop<<std::endl;
        return false;
        default:
        std::cout<<"You Pressed: "<<userop<<std::endl;
        std::cout<<"Invalid Input"<<std::endl;
        break;
    }
    return true;
    i was wondering that instead of like pass by value we could send the address of the object for that do we need a pointer ? or just use & for address ?

**Comment by Z-K11** [comment]
Solved already in the latest commit

**Comment by adeelumar-17** [comment]
Yes you can just use & operator, no need to use pointer
